### ISSUE TITLE
I followed the instructions on Ubuntu 20 LTS and it failed,  

### ISSUE THREAD

**Issue by MisakaMikoto128** [Water-Melon/Melon#1]
![image](https://user-images.githubusercontent.com/60165234/130766458-b306f602-1e8c-46a2-8c19-cb4b9a5045da.png)

**Comment by MisakaMikoto128** [comment]
我知道怎么回事了，没注意报错说明

**Comment by Water-Melon** [comment]
感谢反馈，确实ubuntu会对返回值进行检查，因为加了-Werror所以被作为错误抛出。会尽快修复的

**Comment by Water-Melon** [comment]
已处理，请拉新后重新编一下，感谢反馈 :-)
