### ISSUE TITLE
mingw上无法通过编译

### ISSUE THREAD

**Issue by heheda123123** [Water-Melon/Melon#16]
如图，使用msys2 mingw ucrt
![image](https://github.com/Water-Melon/Melon/assets/97490782/c8b17cab-7573-413e-8992-dcdf1a187eda)

**Comment by Water-Melon** [comment]
我在我的Windows虚机上尝试编译了一下，确实存在编译问题，是近期更新的一些功能代码不兼容windows导致的，但和你截图中的情况不太一样。
目前正在修正这部分编译报错。
此外还请确保你的mingw安装参数与readme中给出的一致：
- Version: 8.1.0
- Architecture: i686
- Threads: posix
- Exception: dwarf
- Build revision: 0

**Comment by heheda123123** [comment]
有几个意见大佬可以参考下哈
1 如果要跨平台支持，最好是支持原生windows，mingw上坑很多
2 如果是支持mingw的话，最好以msys2的为准，现在主流都是用这个环境，gcc，clang都能使用最新的版本。其他地方下载的都是很多年没有更新过的工具链了

**Comment by Water-Melon** [comment]
十分感谢，确实，我不是做Windows开发的，所以对Windows上的情况不是很了解。如果是这样的话，我应该会将这个issue粉两个阶段处理：
1. 在当前支持的mingw版本下，修复编译报错
2. 迁移代码到msys2
非常感谢你的反馈，欢迎加入Melon QQ群，便于大家交流。

**Comment by heheda123123** [comment]
已经在群里了，我可以帮忙做一些迁移到windows的工作，不过首先构建方式得换个跨平台的，现在configure就只能在linux环境下用，都没法迁移代码，后面我写个xmake.lua的构建文件先

**Comment by Water-Melon** [comment]
OK～ 你可否群里说一下，我不知道哪个是你，可以一起讨论一下。

**Comment by Water-Melon** [comment]
目前，readme中给出的mingw版本已经可以通过编译了。msys2的问题再一起讨论一下方案。

**Comment by heheda123123** [comment]
对了，windows的移植一时半会儿做不了。不过msys的问题还是可以完善下。刚刚测试最新的代码仍然有上图的问题
主要就是输出的时候格式化字符串的类型不匹配
除了`%I64u`  `%I64d` `%I64o` `%I64x`这种，可以全部换成`%Ilu` `%Ild``%Ilo``%Ilx`，这个写法windows是支持的
还有下面的
![image](https://github.com/Water-Melon/Melon/assets/97490782/bb62328a-2fa4-4e47-98c7-85f17cecd6d8)

**Comment by Water-Melon** [comment]
刚刚我提交了代码，目前应该已经支持了msys2，可以再试一下，如果没问题就关闭这个issue了。

**Comment by heheda123123** [comment]
我这里测试也编译成功了
