### ISSUE TITLE
fheap算法有误

### ISSUE THREAD

**Issue by Yuandiaodiaodiao** [Water-Melon/Melon#3]
让我们构造一个序列 期望的输出应该是0 288 289 289
而在我本地c++14 msvc的编译之下  输出序列为0 288 289 539 
mln_fheap_consolidate中  while (array[d] != NULL) {
             
                y = array[d];
         
                if (!fh->cmp(x->key, y->key)) {
的交换策略 
与mln_fheap_insert中
  if (!fh->cmp(fn->key, fh->min->key))的交换策略完全相反
`//
// Created by Yuan on 2022/4/17.
//
#include <stdio.h>
#include <stdlib.h>
#include "mln_fheap.h"
#include<iostream>
using namespace std;
static int cmp_handler(const void *key1, const void *key2)
{
    return *(int *)key1 < *(int *)key2? 0: 1;
}

static void copy_handler(void *old_key, void *new_key)
{
    *(int *)old_key = *(int *)new_key;
}

int main(int argc, char *argv[])
{
    int i = 10, min = 0;
    mln_fheap_t *fh;
    mln_fheap_node_t *fn;
    struct mln_fheap_attr fattr;

    fattr.cmp = cmp_handler;
    fattr.copy = copy_handler;
    fattr.key_free = NULL;
    fattr.min_val = &min;
    fattr.min_val_size = sizeof(min);
    fh = mln_fheap_init(&fattr);
int i1=0;
int i21=289;
int i22=288;
int i23=289;
int i31=539;
int i32=538;
int i33=537;
int i34=538;
int i35=539;

//int i3=500;
//int i3=500;
    fn = mln_fheap_node_init(fh, &i1);
    mln_fheap_insert(fh, fn);

    mln_fheap_extract_min(fh);
    cout<<"出队"<<*((int*)fn->key)<<endl;

    fn = mln_fheap_node_init(fh, &i21);
    mln_fheap_insert(fh, fn);
    fn = mln_fheap_node_init(fh, &i22);
    mln_fheap_insert(fh, fn);
    fn = mln_fheap_node_init(fh, &i23);
    mln_fheap_insert(fh, fn);

    fn = mln_fheap_extract_min(fh);
    cout<<"出队"<<*((int*)fn->key)<<endl;
    fn = mln_fheap_node_init(fh, &i31);
    mln_fheap_insert(fh, fn);
    fn = mln_fheap_node_init(fh, &i32);
    mln_fheap_insert(fh, fn);
    fn = mln_fheap_node_init(fh, &i33);
    mln_fheap_insert(fh, fn);
    fn = mln_fheap_node_init(fh, &i34);
    mln_fheap_insert(fh, fn);
    fn = mln_fheap_node_init(fh, &i35);
    mln_fheap_insert(fh, fn);

    fn = mln_fheap_extract_min(fh);
    cout<<"出队"<<*((int*)fn->key)<<endl;
    fn = mln_fheap_extract_min(fh);
    cout<<"出队"<<*((int*)fn->key)<<endl;
    fn = mln_fheap_extract_min(fh);
    cout<<"出队"<<*((int*)fn->key)<<endl;
    fn = mln_fheap_extract_min(fh);
    cout<<"出队"<<*((int*)fn->key)<<endl;
    fn = mln_fheap_extract_min(fh);
    cout<<"出队"<<*((int*)fn->key)<<endl;
    fn = mln_fheap_extract_min(fh);
    cout<<"出队"<<*((int*)fn->key)<<endl;
    mln_fheap_destroy(fh);

    return 0;
}`

**Comment by Water-Melon** [comment]
非常感谢，我在mac下已经复现此问题，并按照您给出的建议修改后可以返回期望顺序。我需要对算法再进行整体检查，修复版本将在周二前合并入主分支，再次感谢您的反馈😊

**Comment by Water-Melon** [comment]
问题已修复，请拉取最新主分支代码。非常感谢您的使用与反馈😊
