### ISSUE TITLE
Compiling failed on MSYS2 gcc-11.2

### ISSUE THREAD

**Issue by Wistral** [Water-Melon/Melon#4]
When compiling on mingw64, got `error: cast to pointer from integer of different size`

>$ make
test -d objs || mkdir objs
test -d lib || mkdir lib
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O3 -fPIC -o objs/mln_lang_file.o ./melang/file/mln_lang_file.c
./melang/file/mln_lang_file.c: In function 'mln_lang_open_process':
./melang/file/mln_lang_file.c:345:41: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  345 |     if ((rn = mln_rbtree_node_new(tree, (void *)fd)) == NULL) {
      |                                         ^
./melang/file/mln_lang_file.c: In function 'mln_lang_close_process':
./melang/file/mln_lang_file.c:939:46: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  939 |     rn = mln_rbtree_search(tree, tree->root, (void *)fd);
      |                                              ^
cc1.exe: all warnings being treated as errors
make: *** [Makefile:90: objs/mln_lang_file.o] Error 1

GCC version
>$ gcc -v
Using built-in specs.
COLLECT_GCC=H:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=H:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-11.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev8, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Rev8, Built by MSYS2 project)

And turn to mingw32, got another error `error: conflicting types for 'inet_ntop'`
>$ make
test -d objs || mkdir objs
test -d lib || mkdir lib
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O3 -fPIC -o objs/mln_lang_network.o ./melang/network/mln_lang_network.c
./melang/network/mln_lang_network.c:180:7: error: conflicting types for 'inet_ntop'; have 'char *(int,  const void *, char *, socklen_t)' {aka 'char *(int,  const void *, char *, int)'}
  180 | char *inet_ntop(int af, const void *src, char* dst, socklen_t size){
      |       ^~~~~~~~~
In file included from ./melang/network/mln_lang_network.c:6:
H:/msys64/mingw32/include/ws2tcpip.h:401:35: note: previous declaration of 'inet_ntop' with type 'const CHAR *(INT,  const void *, CHAR *, size_t)' {aka 'const char *(int,  const void *, char *, unsigned int)'}
  401 | WINSOCK_API_LINKAGE LPCSTR WSAAPI InetNtopA(INT Family, LPCVOID pAddr, LPSTR pStringBuf, size_t StringBufSize);
      |                                   ^~~~~~~~~
make: *** [Makefile:102: objs/mln_lang_network.o] Error 1

With GCC version
>$ gcc -v
Using built-in specs.
COLLECT_GCC=H:\msys64\mingw32\bin\gcc.exe
COLLECT_LTO_WRAPPER=H:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../gcc-11.2.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-w64-mingw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/include --libexecdir=/mingw32/lib --enable-bootstrap --enable-checking=release --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw32 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev10, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--no-seh -Wl,--large-address-aware -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--no-seh -Wl,--large-address-aware' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--no-seh\ -Wl,--large-address-aware\ -Wl,--stack,12582912' --disable-sjlj-exceptions --with-dwarf2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Rev10, Built by MSYS2 project)

MSYS version
>$ uname -a
MSYS_NT-10.0-19043 XXX 3.3.3-341.x86_64 2022-01-18 13:00 UTC x86_64 Msys

melon git branch/commit [3d6329a60941ab198ab9b952ebd2bbdea0c8de49](https://github.com/Water-Melon/Melon/commit/3d6329a60941ab198ab9b952ebd2bbdea0c8de49)

**Comment by Water-Melon** [comment]
you can try to use this [MingW-W64-builds](https://www.mingw-w64.org/downloads/#mingw-builds)

**Comment by Wistral** [comment]
I also tried on ubuntu 20.04, up to gcc version 10.3.0 is compiling-compatible.
Still, gcc 11.x failed by errors like 
`error: array subscript 'struct sockaddr_in6[0]' is partly outside array bounds of 'struct sockaddr[1]' [-Werror=array-bounds]`

More detailed reasons need to inspect...

**Comment by Water-Melon** [comment]
Thanks for your feedback. I have updated code for win32, please pull and try MinGW-w64(gcc 8.1.0) again. And I will check about the warning on gcc 11.x later. Thanks a lot.😊

**Comment by Water-Melon** [comment]
The gcc 11.x warning has been fixed, but it is not recommended to use this version to compile, because the out-of-order execution of the O3 optimization of the version 11.x was found to cause GP exceptions during the test. Therefore, for the gcc 11.x, use O2 optimization instead O3, so there will be a decrease in performance.

**Comment by Wistral** [comment]
Yes, gcc 11.1.0 compiling can pass now, thanks.
However, mingw64/gcc 11.2 still stucked by errors.
Some because of warning,
>gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_lang_file.o ./melang/file/mln_lang_file.c
./melang/file/mln_lang_file.c: In function 'mln_lang_open_process':
./melang/file/mln_lang_file.c:345:41: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  345 |     if ((rn = mln_rbtree_node_new(tree, (void *)fd)) == NULL) {
      |                                         ^
./melang/file/mln_lang_file.c: In function 'mln_lang_close_process':
./melang/file/mln_lang_file.c:939:46: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  939 |     rn = mln_rbtree_search(tree, tree->root, (void *)fd);
      |                                              ^
cc1.exe: all warnings being treated as errors
make: *** [Makefile:90: objs/mln_lang_file.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_lang_sys.o ./melang/sys/mln_lang_sys.c
./melang/sys/mln_lang_sys.c: In function 'mln_lang_sys_str_process':
./melang/sys/mln_lang_sys.c:660:55: error: format '%d' expects argument of type 'int', but argument 4 has type 'mln_s64_t' {aka 'long long int'} [-Werror=format=]
  660 |                 n = snprintf(buf, sizeof(buf)-1, "%I64d", val->data.i);
      |                                                   ~~~~^   ~~~~~~~~~~~
      |                                                       |            |
      |                                                       int          mln_s64_t {aka long long int}
      |                                                   %I64lld
cc1.exe: all warnings being treated as errors
make: *** [Makefile:114: objs/mln_lang_sys.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_bignum.o ./src/mln_bignum.c
./src/mln_bignum.c: In function 'mln_bignum_dump':
./src/mln_bignum.c:898:32: error: 'I' flag used with '%x' gnu_printf format [-Werror=format=]
  898 |         fprintf(stderr, "\t%I64x\n", bn->data[i]);
      |                                ^
./src/mln_bignum.c:898:32: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'mln_u64_t' {aka 'long long unsigned int'} [-Werror=format=]
  898 |         fprintf(stderr, "\t%I64x\n", bn->data[i]);
      |                            ~~~~^     ~~~~~~~~~~~
      |                                |             |
      |                                unsigned int  mln_u64_t {aka long long unsigned int}
      |                            %I64llx
cc1.exe: all warnings being treated as errors
make: *** [Makefile:124: objs/mln_bignum.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_conf.o ./src/mln_conf.c
./src/mln_conf.c: In function 'mln_conf_dump_domain_scan':
./src/mln_conf.c:918:34: error: format '%d' expects argument of type 'int', but argument 2 has type 'mln_sauto_t' {aka 'long long int'} [-Werror=format=]
  918 |                 printf("INT [%I64d]\n", ci->val.i);
      |                              ~~~~^      ~~~~~~~~~
      |                                  |             |
      |                                  int           mln_sauto_t {aka long long int}
      |                              %I64lld
cc1.exe: all warnings being treated as errors
make: *** [Makefile:128: objs/mln_conf.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_json.o ./src/mln_json.c
./src/mln_json.c: In function 'mln_json_write_content':
./src/mln_json.c:737:45: error: format '%d' expects argument of type 'int', but argument 4 has type 'mln_s64_t' {aka 'long long int'} [-Werror=format=]
  737 |                 n = snprintf(buf, 512, "%I64d", i);
      |                                         ~~~~^   ~
      |                                             |   |
      |                                             int mln_s64_t {aka long long int}
      |                                         %I64lld
./src/mln_json.c: In function 'mln_json_dump':
./src/mln_json.c:986:21: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'mln_uauto_t' {aka 'long long unsigned int'} [-Werror=format=]
  986 |     printf("index:%lu ", j->index);
      |                   ~~^    ~~~~~~~~
      |                     |     |
      |                     |     mln_uauto_t {aka long long unsigned int}
      |                     long unsigned int
      |                   %llu
cc1.exe: all warnings being treated as errors
make: *** [Makefile:160: objs/mln_json.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_lang.o ./src/mln_lang.c
./src/mln_lang.c: In function 'mln_lang_var_toint':
./src/mln_lang.c:1866:38: error: format '%d' expects argument of type 'int *', but argument 3 has type 'mln_s64_t *' {aka 'long long int *'} [-Werror=format=]
 1866 |             sscanf((char *)buf, "%I64d", &i);
      |                                  ~~~~^   ~~
      |                                      |   |
      |                                      |   mln_s64_t * {aka long long int *}
      |                                      int *
      |                                  %I64lld
./src/mln_lang.c: In function 'mln_lang_var_tostring':
./src/mln_lang.c:1942:51: error: format '%d' expects argument of type 'int', but argument 4 has type 'mln_s64_t' {aka 'long long int'} [-Werror=format=]
 1942 |             n = snprintf(buf, sizeof(buf)-1, "%I64d", val->data.i);
      |                                               ~~~~^   ~~~~~~~~~~~
      |                                                   |            |
      |                                                   int          mln_s64_t {aka long long int}
      |                                               %I64lld
cc1.exe: all warnings being treated as errors
make: *** [Makefile:162: objs/mln_lang.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_lang_ast.o ./src/mln_lang_ast.c
./src/mln_lang_ast.c: In function 'mln_lang_semantic_factorint':
./src/mln_lang_ast.c:3197:30: error: 'I' flag used with '%x' gnu_scanf format [-Werror=format=]
 3197 |             sscanf(num, "%I64x", &i);
      |                              ^
./src/mln_lang_ast.c:3197:30: error: format '%x' expects argument of type 'unsigned int *', but argument 3 has type 'mln_s64_t *' {aka 'long long int *'} [-Werror=format=]
 3197 |             sscanf(num, "%I64x", &i);
      |                          ~~~~^   ~~
      |                              |   |
      |                              |   mln_s64_t * {aka long long int *}
      |                              unsigned int *
      |                          %I64llx
./src/mln_lang_ast.c:3205:30: error: 'I' flag used with '%o' gnu_scanf format [-Werror=format=]
 3205 |             sscanf(num, "%I64o", &i);
      |                              ^
./src/mln_lang_ast.c:3205:30: error: format '%o' expects argument of type 'unsigned int *', but argument 3 has type 'mln_s64_t *' {aka 'long long int *'} [-Werror=format=]
 3205 |             sscanf(num, "%I64o", &i);
      |                          ~~~~^   ~~
      |                              |   |
      |                              |   mln_s64_t * {aka long long int *}
      |                              unsigned int *
      |                          %I64llo
./src/mln_lang_ast.c:3214:26: error: format '%d' expects argument of type 'int *', but argument 3 has type 'mln_s64_t *' {aka 'long long int *'} [-Werror=format=]
 3214 |         sscanf(num, "%I64d", &i);
      |                      ~~~~^   ~~
      |                          |   |
      |                          |   mln_s64_t * {aka long long int *}
      |                          int *
      |                      %I64lld
cc1.exe: all warnings being treated as errors
make: *** [Makefile:166: objs/mln_lang_ast.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_lex.o ./src/mln_lex.c
./src/mln_lex.c: In function 'mln_lex_strerror':
./src/mln_lex.c:360:51: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'mln_u64_t' {aka 'long long unsigned int'} [-Werror=format=]
  360 |     n += snprintf(lex->err_msg + n, len - n, "%I64u: %s", lex->line, mln_lex_errmsg[lex->error]);
      |                                               ~~~~^       ~~~~~~~~~
      |                                                   |          |
      |                                                   |          mln_u64_t {aka long long unsigned int}
      |                                                   unsigned int
      |                                               %I64llu
cc1.exe: all warnings being treated as errors
make: *** [Makefile:182: objs/mln_lex.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_log.o ./src/mln_log.c
./src/mln_log.c: In function '_mln_sys_log_process':
./src/mln_log.c:434:69: error: format '%d' expects argument of type 'int', but argument 4 has type 'mln_sauto_t' {aka 'long long int'} [-Werror=format=]
  434 |                 int n = snprintf(line_str, sizeof(line_str)-1, "%I64d", num);
      |                                                                 ~~~~^   ~~~
      |                                                                     |   |
      |                                                                     int mln_sauto_t {aka long long int}
      |                                                                 %I64lld
./src/mln_log.c:501:69: error: format '%d' expects argument of type 'int', but argument 4 has type 'long long int' [-Werror=format=]
  501 |                 int n = snprintf(line_str, sizeof(line_str)-1, "%I64d", num);
      |                                                                 ~~~~^   ~~~
      |                                                                     |   |
      |                                                                     int long long int
      |                                                                 %I64lld
./src/mln_log.c:517:69: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'long long unsigned int' [-Werror=format=]
  517 |                 int n = snprintf(line_str, sizeof(line_str)-1, "%I64u", num);
      |                                                                 ~~~~^   ~~~
      |                                                                     |   |
      |                                                                     |   long long unsigned int
      |                                                                     unsigned int
      |                                                                 %I64llu
cc1.exe: all warnings being treated as errors
make: *** [Makefile:184: objs/mln_log.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_matrix.o ./src/mln_matrix.c
./src/mln_matrix.c: In function 'mln_matrix_dump':
./src/mln_matrix.c:144:25: error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'mln_size_t' {aka 'long long unsigned int'} [-Werror=format=]
  144 |     printf("Matrix row:%u col:%u\n ", matrix->row, matrix->col);
      |                        ~^             ~~~~~~~~~~~
      |                         |                   |
      |                         unsigned int        mln_size_t {aka long long unsigned int}
      |                        %llu
./src/mln_matrix.c:144:32: error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'mln_size_t' {aka 'long long unsigned int'} [-Werror=format=]
  144 |     printf("Matrix row:%u col:%u\n ", matrix->row, matrix->col);
      |                               ~^                   ~~~~~~~~~~~
      |                                |                         |
      |                                unsigned int              mln_size_t {aka long long unsigned int}
      |                               %llu
cc1.exe: all warnings being treated as errors
make: *** [Makefile:186: objs/mln_matrix.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_md5.o ./src/mln_md5.c
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_melang.o ./src/mln_melang.c
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_parser_generator.o ./src/mln_parser_generator.c
./src/mln_parser_generator.c: In function 'mln_pg_output_state':
./src/mln_parser_generator.c:871:27: error: format '%d' expects argument of type 'int', but argument 2 has type 'mln_sauto_t' {aka 'long long int'} [-Werror=format=]
  871 |         printf("State %I64d: input: [%s] nr_item:%I64u\n", \
      |                       ~~~~^
      |                           |
      |                           int
      |                       %I64lld
  872 |                s->id, \
      |                ~~~~~
      |                 |
      |                 mln_sauto_t {aka long long int}
./src/mln_parser_generator.c:871:54: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'long long unsigned int' [-Werror=format=]
  871 |         printf("State %I64d: input: [%s] nr_item:%I64u\n", \
      |                                                  ~~~~^
      |                                                      |
      |                                                      unsigned int
      |                                                  %I64llu
......
  874 |                (unsigned long long)(s->nr_item));
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                |
      |                long long unsigned int
./src/mln_parser_generator.c:889:45: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'mln_sauto_t' {aka 'long long int'} [-Werror=format=]
  889 |             printf("\t\tread:[%s] goto_id:%ld", it->read==NULL?"(null)":(char *)(it->read->token->data), it->goto_id);
      |                                           ~~^
                 ~~~~~~~~~~~
      |                                             |
                   |
      |                                             long int
                   mln_sauto_t {aka long long int}
      |                                           %lld
cc1.exe: all warnings being treated as errors
make: *** [Makefile:192: objs/mln_parser_generator.o] Error 1
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_path.o ./src/mln_path.c
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_prime_generator.o ./src/mln_prime_generator.c
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_queue.o ./src/mln_queue.c
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_rbtree.o ./src/mln_rbtree.c
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_rc.o ./src/mln_rc.c
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_regexp.o ./src/mln_regexp.c
gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_rs.o ./src/mln_rs.c
./src/mln_rs.c: In function 'mln_rs_matrix_dump':
./src/mln_rs.c:362:25: error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'mln_size_t' {aka 'long long unsigned int'} [-Werror=format=]
  362 |     printf("Matrix row:%u col:%u\n ", matrix->row, matrix->col);
      |                        ~^             ~~~~~~~~~~~
      |                         |                   |
      |                         unsigned int        mln_size_t {aka long long unsigned int}
      |                        %llu
./src/mln_rs.c:362:32: error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'mln_size_t' {aka 'long long unsigned int'} [-Werror=format=]
  362 |     printf("Matrix row:%u col:%u\n ", matrix->row, matrix->col);
      |                               ~^                   ~~~~~~~~~~~
      |                                |                         |
      |                                unsigned int              mln_size_t {aka long long unsigned int}
      |                               %llu
cc1.exe: all warnings being treated as errors
make: *** [Makefile:206: objs/mln_rs.o] Error 1




others because of API duplicated.
>gcc -Iinclude -Imelang -c -Wall -ggdb -Werror -O2 -fPIC -o objs/mln_lang_network.o ./melang/network/mln_lang_network.c
./melang/network/mln_lang_network.c:180:7: error: conflicting types for 'inet_ntop'; have 'char *(int,  const void *, char *, socklen_t)' {aka 'char *(int,  const void *, char *, int)'}
  180 | char *inet_ntop(int af, const void *src, char* dst, socklen_t size){
      |       ^~~~~~~~~
In file included from ./melang/network/mln_lang_network.c:6:
H:/msys64/mingw64/include/ws2tcpip.h:401:35: note: previous declaration of 'inet_ntop' with type 'const CHAR *(INT,  const void *, CHAR *, size_t)' {aka 'const char *(int,  const void *, char *, long long unsigned int)'}
  401 | WINSOCK_API_LINKAGE LPCSTR WSAAPI InetNtopA(INT Family, LPCVOID pAddr, LPSTR pStringBuf, size_t StringBufSize);
      |                                   ^~~~~~~~~
make: *** [Makefile:102: objs/mln_lang_network.o] Error 1

conflict definition in `H:\msys64\mingw64\include\ws2tcpip.h`
macro defined scope of `#if (_WIN32_WINNT >= 0x0600)`

so I just simply walkaround by override _WIN32_WINNT definition by manual compile with

`gcc -D_WIN32_WINNT=0x500 -Iinclude -Imelang -c -Wall -ggdb -O2 -fPIC -o objs/mln_lang_network.o ./melang/network/mln_lang_network.c`

Then it works, but may cause unknown runtime error...
Are there any unit tests to refer?

Network relative cross-platform port is really complicated

**Comment by Water-Melon** [comment]
What are your mingw-w64 installation settings when you install mingw-w64? My settings are:
Version: 8.1.0
Architecture: i686
Threads: posix
Exception: dwarf
Build revision: 0

**Comment by Wistral** [comment]
It is not [MingW-W64-builds](https://www.mingw-w64.org/downloads/#mingw-builds) but [MSYS2](https://www.mingw-w64.org/downloads/#msys2).

>$ gcc -v
Using built-in specs.
COLLECT_GCC=H:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=H:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-11.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev10, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' LDFLAGS_FOR_TARGET=-pipe --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Rev10, Built by MSYS2 project)
$ uname -a
MINGW64_NT-10.0-19043  3.3.4-341.x86_64 2022-02-15 17:24 UTC x86_64 Msys


MingW-W64-builds is already OK, but not for MSYS platform.

btw., if you think it is not very meaningful to fix for MSYS, I can close it,
since MingW-W64 should meet my use.

**Comment by Water-Melon** [comment]
In fact, I have no plans to support Windows further recently. The reason for supporting Windows is so that the scripting languages in this library can run on Windows. In addition, some algorithms, data structures and other components can also be integrated and used by programs on Windows.

**Comment by Wistral** [comment]
I've got it, you are right. Thanks.
