### ISSUE TITLE
melon.conf文件无效

### ISSUE THREAD

**Issue by blackzw** [Water-Melon/Melon#5]
项目目录：
<project dir>
+ inc
   + melon
       + *.h
+ lib
   + melon
        + libmelon.so
 + conf
    + melon.conf
 + src
     + *.c
 + logs
 
 发现不管如何编译，最后默认的log文件保存的地方都是"{{ROOT}}/logs/melon.log"

**Comment by Water-Melon** [comment]
感谢使用😊
编译安装后，会在指定的prefix下放置一个logs目录用来存放日志文件，但有三种方式可以让您把日志写入别的文件中：
1、修改安装路径下的conf/melon.conf文件中log_path配置项
2、在程序中调用mln_path_hook_set接管路径查询处理函数，在里面给出您期望的路径（需要保证父级以上目录存在）
3、在程序中调用mln_log_set_logger来接管日志处理函数，这样就可以自定义日志处理，以及要写入的文件
三种方式可以任选其一。

**Comment by Water-Melon** [comment]
感谢使用，如还有问题欢迎随时发起issue或QQ群联系😊
