### ISSUE TITLE
我想在Windows系统上用，linux和Windows头文件不一样，我自己改不成

### ISSUE THREAD

**Issue by fgfxf** [Water-Melon/Melon#8]
我想在Windows系统上用，linux和Windows头文件不一样，我自己改不成。
请问可否把Windows能用部分整合一下？或者用C++11标准？

**Comment by Water-Melon** [comment]
> 我想在Windows系统上用，linux和Windows头文件不一样，我自己改不成。
请问可否把Windows能用部分整合一下？

可否给出一个例子？
一般Melon使用的时候只需要include对应模块头文件即可，头文件内会对win或其他平台有宏控制。如果想使用win的api，可以在自己的源文件中include即可，一般不太需要改Melon模块的头文件。
另外，在Windows上Melon的框架部分无法使用，其余模块均不受影响。


> 或者用C++11标准？

暂时并未打算支持C++编译器，如果需要在C++中使用，还请先编译成库，然后在C++文件中这样引入头文件：
```c
extern "C" {
  #include "mln_xxx.h"
  ...
}
```
最后在编译时`-I`参数指定头文件路径，连接时使用`-lmelon`连接melon库，且使用`-L`指定库路径。
